name: rock-dev-env
services:
  sql-server:
    image: "<Name of your Dockerhub repo/image:tag>"
    container_name: sql-server
    ports:
      - 1433:1433

#Rock web docker image
  rock:
    image: "<Name of your Dockerhub repo/image:tag>"
    container_name: rock
    ports:
      - 9000:80
      - 9001:443
    links:
      - sql-server
    